#use_frameworks!

platform :ios, '8.0'

target 'LuaOC_Example' do
  pod 'LuaOC', :path => '../'
end
target 'LuaOC_Tests' do
    inherit! :search_paths
    
#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
end
